; FITWORK Windows installer - Inno Setup script.
;
; IMPORTANT - written and reviewed, but NOT compiled or run: this repo is
; developed in a Linux sandbox with no access to a Windows machine, Inno
; Setup, or its ISCC compiler. Every Pascal Script function below follows
; Inno Setup's documented, long-stable scripting API as precisely as I can
; write it from specification, but it has not been verified by an actual
; compile-and-run pass. Compile this on a real Windows machine with Inno
; Setup installed (https://jrsoftware.org/isinfo.php) and fix forward from
; whatever ISCC reports - see installer/README.md for the full build steps
; and a manual test checklist for everything only a real Windows box can
; confirm.
;
; Expects installer/build.ps1 to have already run npm build + staged a
; production-only server/node_modules + a portable Node runtime + nssm.exe
; + mkcert.exe into installer/dist/stage/ before this script is compiled -
; see build.ps1 for exactly what it assembles and where.

#define AppName "FITWORK"
#define AppVersion "1.0.0"
#define AppPublisher "FITWORK"
// Default only - the actual port used by a given install is whatever the
// PortPage wizard question resolves to at runtime (see GetPort() in
// [Code]), not this compile-time constant. Still needed as the seed value
// for PortPage.Values[0] below, since that assignment runs before the user
// has answered anything.
#define AppPort "8443"
#define ServiceName "FITWORK"
#define StageDir "dist\stage"

[Setup]
; Fixed GUID - do not change between versions, or Windows will treat every
; release as a fresh, separate install instead of an in-place upgrade.
AppId={{B6C1B6C0-6E7E-4F4F-9B7E-FITWORK00001}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
; Installing a Windows Service, a firewall rule, and changing power settings
; all require elevation - request it once, up front, rather than per-step.
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible
OutputDir=dist
OutputBaseFilename=FITWORK-Setup-{#AppVersion}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\server\dist\index.js

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Dirs]
Name: "{app}\data"
Name: "{app}\data\backups"
Name: "{app}\storage"
Name: "{app}\server\logs"

[Files]
; Everything under installer\dist\stage\ is assembled by build.ps1:
;   stage\node\...          portable Node runtime (node.exe + deps)
;   stage\nssm\nssm.exe     service wrapper
;   stage\mkcert\mkcert.exe automatic HTTPS cert generation (Server mode)
;   stage\server\...        server\dist, server\prisma, server\package.json,
;                           a *production-only* server\node_modules
;   stage\client\...        client\dist (built SPA)
; server\.env is deliberately NOT staged here - it's generated by this
; installer's [Code] section after the mode-picker page, never shipped as
; a static file, so it always reflects what was actually chosen at install
; time rather than a stale template.
Source: "{#StageDir}\node\*"; DestDir: "{app}\vendor\node"; Flags: recursesubdirs ignoreversion
Source: "{#StageDir}\nssm\nssm.exe"; DestDir: "{app}\vendor\nssm"; Flags: ignoreversion
; Used by SetupHttpsForServerMode in [Code] to generate the HTTPS
; certificate automatically during a Server-mode install - see build.ps1
; for where this is downloaded from.
Source: "{#StageDir}\mkcert\mkcert.exe"; DestDir: "{app}\vendor\mkcert"; Flags: ignoreversion
Source: "{#StageDir}\server\*"; DestDir: "{app}\server"; Flags: recursesubdirs ignoreversion; Excludes: ".env,.env.example"
; The running app resolves the client bundle as ../../client/dist relative
; to server/dist/index.js (see server/src/index.ts) - DestDir here MUST be
; {app}\client\dist, not {app}\client, to match, even though build.ps1's
; own staging folder for it is just called "client" (its contents ARE
; client/dist's contents, one level shallower than the installed layout).
Source: "{#StageDir}\client\*"; DestDir: "{app}\client\dist"; Flags: recursesubdirs ignoreversion
Source: "Setup-HTTPS.bat"; DestDir: "{app}"; Flags: ignoreversion
; createAdmin.js/recoveryTool.js themselves need no separate [Files] entry -
; they live under server/src/cli/ (compiled via the normal npm run build,
; same as printLanIp.ts/setupCerts.ts already do) and ship automatically as
; part of the server\* recursive copy above. Only this launcher is new.
Source: "Recovery-Tool.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\docs\INSTALL.md"; DestDir: "{app}\docs"; Flags: ignoreversion
Source: "..\docs\RECOVERY.md"; DestDir: "{app}\docs"; Flags: ignoreversion

; Extracted to {tmp} (NOT installed to {app}) for use DURING the wizard,
; before real installation happens - the wizard's mode-picker/server-options
; pages run entirely before [Files] gets copied to {app}, so the detector
; can't reach for {app}\vendor\node\node.exe yet; it isn't there. printLanIp
; only needs network.js (os/fs/child_process are Node built-ins, no other
; local dependency, no node_modules needed at all for this one tiny script).
; All three DestDir as plain "{tmp}", not a subdirectory - found live that
; ExtractTemporaryFile's DestName has to be a bare filename (Inno Setup
; extracts dontcopy files flat into {tmp} regardless of any subdirectory
; given here), so printLanIp.js and network.js land as siblings; see
; printLanIp.ts's own comment for how it locates network.js given that.
Source: "{#StageDir}\node\node.exe"; DestDir: "{tmp}"; Flags: dontcopy
Source: "{#StageDir}\server\dist\cli\printLanIp.js"; DestDir: "{tmp}"; Flags: dontcopy
Source: "{#StageDir}\server\dist\lib\network.js"; DestDir: "{tmp}"; Flags: dontcopy

[Icons]
; A Windows shortcut whose Filename is a URL opens it in the default
; browser - no separate .url file or launcher script needed. No bundled
; .ico asset, so these use Explorer's default icon rather than pointing
; IconFilename at something that can't actually supply one (a .js file
; has no icon resource; node.exe's is generic and not worth the wiring).
; {code:GetAppUrl} rather than a literal http://localhost:{#AppPort} - these
; shortcuts are created from PortPage's actual chosen value (see [Code]),
; which may differ from the {#AppPort} compile-time default.
Name: "{autodesktop}\{#AppName}"; Filename: "{code:GetAppUrl}"
Name: "{group}\{#AppName}"; Filename: "{code:GetAppUrl}"
Name: "{group}\Open Server Folder"; Filename: "{app}\server"
; Server-mode installs now get HTTPS set up automatically during install
; (see SetupHttpsForServerMode in [Code]) - this shortcut is now a manual
; fallback/regenerate tool (e.g. after the LAN IP changes, or to add an
; extra hostname), not the primary way to get HTTPS working.
Name: "{group}\Regenerate HTTPS Certificate (optional)"; Filename: "{app}\Setup-HTTPS.bat"
Name: "{group}\Uninstall {#AppName}"; Filename: "{uninstallexe}"

[Run]
; Database setup, service install/config/start, and firewall/power settings
; all moved into [Code]'s RunPostInstallSteps (called from CurStepChanged on
; ssPostInstall, same place .env is generated) instead of living here as
; declarative entries. Found live that migrate deploy failed validation
; (P1012, missing DATABASE_URL) and the service crash-looped afterward, but
; the installer reported success regardless - a declarative [Run] entry's
; exit code is never checked by Inno Setup unless you do it yourself, so
; every step here needed that, not just the one that happened to fail
; first. See RunPostInstallSteps and its RunStep helper.

[UninstallRun]
; Runs BEFORE Inno Setup deletes any files, so nssm.exe is still present.
Filename: "{app}\vendor\nssm\nssm.exe"; Parameters: "stop {#ServiceName}"; Flags: runhidden; RunOnceId: "FitWorkStopService"
Filename: "{app}\vendor\nssm\nssm.exe"; Parameters: "remove {#ServiceName} confirm"; Flags: runhidden; RunOnceId: "FitWorkRemoveService"
Filename: "{sys}\netsh.exe"; Parameters: "advfirewall firewall delete rule name=""{#AppName}"""; Flags: runhidden; RunOnceId: "FitWorkRemoveFirewallRule"

[Code]
var
  ModePage: TInputOptionWizardPage;
  PortPage: TInputQueryWizardPage;
  ServerOptionsPage: TInputOptionWizardPage;
  AdminPage: TInputQueryWizardPage;
  BackupAdminPage: TInputQueryWizardPage;
  LanIpLabel: TNewStaticText;
  DetectedLanIpCache: String;
  LanIpDetected: Boolean;
  // Collects one line per failed non-critical RunStep call (see below),
  // shown together in a single summary MsgBox at the end instead of one
  // popup per failure.
  StepWarnings: String;
  // Set once RunPostInstallSteps has actually tried (or skipped) HTTPS
  // setup, read later by CurPageChanged's wpFinished handler to decide
  // which message to show - ssPostInstall (where RunPostInstallSteps runs)
  // always completes before the wizard reaches its Finished page, so this
  // is safe to read there unconditionally. Declared here (not local to
  // SetupHttpsForServerMode, further down the file) because CurPageChanged,
  // which reads it, is defined earlier in the file than that procedure -
  // Pascal Script requires a var declared before its first use.
  HttpsConfigured: Boolean;

// True once the mode picker page has actually been reached/answered -
// Check: functions run during the [Run]/[UninstallRun] phase, long after
// the wizard pages are gone, so they read the pages' final selected state,
// not anything about whether the page was skipped.
//
// Reads the Server checkbox's own state (.Values[1]) directly, not the
// page's computed SelectedValueIndex - found in the field that .env came
// out with SERVER_MODE=standalone on at least one run where Server mode
// was chosen, and could not pin down conclusively from this file alone why
// SelectedValueIndex would misreport that. .Values[i] is the checkbox's
// literal checked state (exclusive pages guarantee exactly one of
// Values[0]/Values[1] is True), one layer more direct/unambiguous than a
// separately-computed index - functionally equivalent if
// SelectedValueIndex was actually fine, strictly safer if it wasn't.
function IsServerMode(): Boolean;
begin
  Result := (ModePage <> nil) and ModePage.Values[1];
end;

// True iff S is non-empty and every character is a digit 0-9 - used by
// NextButtonClick's port validation instead of Delphi's Val() procedure,
// which (caught only by an actual ISCC compile, not by reading the script)
// does not exist in Inno Setup's Pascal Script: it has no Val identifier at
// all, built-in or otherwise. StrToIntDef alone can't replace it either,
// since it silently accepts some malformed input (leading '+', trailing
// whitespace inside the string, etc.) as a parsed number instead of
// rejecting it - checking the string is all digits first, then parsing,
// keeps the original "reject anything but a plain number" intent.
function IsAllDigits(const S: String): Boolean;
var
  I: Integer;
begin
  Result := S <> '';
  for I := 1 to Length(S) do
  begin
    if (S[I] < '0') or (S[I] > '9') then
    begin
      Result := False;
      Exit;
    end;
  end;
end;

// The port this install actually uses - PortPage's answer (validated as
// 1-65535 in NextButtonClick), defaulting to {#AppPort}. Every place that
// used to reference {#AppPort} directly (the .env PORT value, the firewall
// rule, the Icons shortcuts via GetAppUrl below, and the wizard's own
// on-screen messages) now goes through this instead, so a non-default
// choice is threaded through consistently rather than only some of them
// picking it up.
function GetPort(): String;
begin
  if PortPage <> nil then
    Result := Trim(PortPage.Values[0])
  else
    Result := '{#AppPort}';
end;

// {code:...} constant for [Icons]' Filename - called after the wizard is
// done (icons are created during real installation, not during the
// pre-install pages), so GetPort() already reflects whatever was actually
// chosen by this point. Takes a Param string because every {code:...}
// constant function must, per Inno Setup's required signature - unused here
// since there's nothing to parameterize.
function GetAppUrl(Param: String): String;
begin
  Result := 'http://localhost:' + GetPort();
end;

function ShouldAddFirewallRule(): Boolean;
begin
  Result := IsServerMode() and (ServerOptionsPage <> nil) and ServerOptionsPage.Values[0];
end;

function ShouldDisableSleep(): Boolean;
begin
  Result := IsServerMode() and (ServerOptionsPage <> nil) and ServerOptionsPage.Values[1];
end;

// Cached (checked once, reused for the rest of Setup) rather than
// re-checked wherever it's needed - the SAME value has to be used both
// here (to skip the admin-account pages) and later in
// RunPostInstallSteps (to skip actually creating an admin), and by the
// time RunPostInstallSteps runs, migrate deploy has already executed and
// may have freshly created fitwork.db on what really was a clean install -
// checking fresh at that point would wrongly look like "existing
// database" every time. The first call happens from ShouldSkipPage during
// wizard navigation, which only happens after wpSelectDir (the Select
// Destination page) has already completed, so {app} already reflects
// whatever install directory was actually chosen.
var
  DatabaseExistsChecked: Boolean;
  DatabaseExistsCache: Boolean;

function ExistingDatabaseFound(): Boolean;
begin
  if not DatabaseExistsChecked then
  begin
    DatabaseExistsCache := FileExists(ExpandConstant('{app}\data\fitwork.db'));
    DatabaseExistsChecked := True;
  end;
  Result := DatabaseExistsCache;
end;

// Server Mode Options (firewall/sleep checkboxes, LAN IP display) only
// makes sense after picking Server mode - found live that this page showed
// unconditionally on every install, Standalone included, because nothing
// here ever told Inno Setup to skip it.
//
// The admin-account pages (#19) are skipped entirely when a database from
// a previous install already exists at the chosen install path - found
// live: PrepareToInstall's fix for #18 (stop/remove the old service so
// file copy can proceed) does not touch {app}\data, so reinstalling over
// an existing install left the old fitwork.db - and its already-existing
// 'admin' user - in place. Creating the admin account then hit a unique-
// constraint violation and aborted the whole install with nothing but an
// exit code (see RunPostInstallSteps). Rather than surface that as a
// wizard validation error, don't ask for admin details at all when
// there's clearly already a working system underneath - matches
// RunPostInstallSteps' own skip of the actual creation step below.
function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := ((PageID = ServerOptionsPage.ID) and not IsServerMode()) or
    (((PageID = AdminPage.ID) or (PageID = BackupAdminPage.ID)) and ExistingDatabaseFound());
end;

// Shells out to the exact same detectLanIp() the running app itself uses
// (server/src/lib/network.ts, via the small server/src/cli/printLanIp.ts
// entry point) rather than reimplementing adapter-preference logic here -
// Exec() can't capture stdout directly, so this routes through cmd.exe
// with a redirect to a temp file and reads that back. Runs against the
// dontcopy-extracted {tmp} copies (see [Files]), not {app}\... - this is
// called from the pre-install wizard, before the real app files exist.
function DetectLanIpViaApp(): String;
var
  ResultCode: Integer;
  OutFile: String;
  Output: AnsiString;
  NodeExe: String;
  ScriptPath: String;
begin
  Result := '';
  ExtractTemporaryFile('node.exe');
  ExtractTemporaryFile('printLanIp.js');
  ExtractTemporaryFile('network.js');

  OutFile := ExpandConstant('{tmp}\fitwork-lan-ip.txt');
  NodeExe := ExpandConstant('{tmp}\node.exe');
  ScriptPath := ExpandConstant('{tmp}\printLanIp.js');

  if Exec(ExpandConstant('{cmd}'),
     '/C ""' + NodeExe + '" "' + ScriptPath + '" > "' + OutFile + '" 2>&1"',
     '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
  begin
    if LoadStringFromFile(OutFile, Output) then
      Result := Trim(String(Output));
  end;

  if (Result = '') or (Result = 'NONE') then
    Result := 'unknown - check this PC''s network adapters manually';
end;

procedure InitializeWizard();
begin
  ModePage := CreateInputOptionPage(wpSelectDir,
    'Choose Install Mode',
    'How will other computers use this installation?',
    'Select one, then click Next:',
    True, False);
  ModePage.Add('Standalone - this PC only (no other computers can connect)');
  ModePage.Add('Server - other PCs on this network will connect to this one');
  ModePage.SelectedValueIndex := 0;

  // Asked for both modes, not just Server - Standalone still binds this
  // port on localhost, so a conflict with another program on this PC
  // matters either way. Placed before ServerOptionsPage/AdminPage/
  // BackupAdminPage (chained off PortPage.ID below) so GetPort() already
  // has its final answer by the time anything downstream - the firewall
  // rule text, the LAN IP label, .env - needs to read it.
  PortPage := CreateInputQueryPage(ModePage.ID,
    'Network Port',
    'Which port should FITWORK listen on?',
    'The default (8443) works for almost every install. Only change this if you know you need to - for ' +
    'example, another program on this PC is already using 8443. Whatever you choose here is threaded ' +
    'through the app itself, the Windows Firewall rule, and every shortcut/message that shows the ' +
    'connection address.');
  PortPage.Add('Port:', False);
  PortPage.Values[0] := '{#AppPort}';

  ServerOptionsPage := CreateInputOptionPage(PortPage.ID,
    'Server Mode Options',
    'These only apply because you chose Server mode.',
    'Recommended for most installs - leave both checked unless you have a reason not to:',
    False, False);
  ServerOptionsPage.Add('Add a Windows Firewall rule so other PCs can reach this one on port ' + GetPort());
  ServerOptionsPage.Add('Prevent this PC from sleeping, so staff can always reach the server');
  ServerOptionsPage.Values[0] := True;
  ServerOptionsPage.Values[1] := True;

  // Static info label showing the detected LAN address, added directly to
  // the options page's surface above its checkboxes (the page type itself
  // has no built-in slot for arbitrary extra text beyond its captions).
  LanIpLabel := TNewStaticText.Create(WizardForm);
  LanIpLabel.Parent := ServerOptionsPage.Surface;
  LanIpLabel.Left := 0;
  LanIpLabel.Top := ServerOptionsPage.CheckListBox.Top + ServerOptionsPage.CheckListBox.Height + 16;
  LanIpLabel.Width := ServerOptionsPage.SurfaceWidth;
  LanIpLabel.WordWrap := True;
  LanIpLabel.Caption := 'Detecting this PC''s LAN address...';
  LanIpDetected := False;

  // Every install needs at least one admin account or nobody can ever log
  // in - shown unconditionally (both modes), not gated by IsServerMode()/
  // ShouldSkipPage. Found live: the installer previously shipped no way to
  // create this account at all (no scripts\, no tsx, npm run create-admin
  // unavailable on an installed machine) - a fresh install ran and reported
  // success with a totally unusable, unrecoverable system underneath.
  AdminPage := CreateInputQueryPage(ServerOptionsPage.ID,
    'Create Admin Accounts',
    'These log into FITWORK itself once it''s running - separate from this installer.',
    'Enter the primary admin account below.');
  AdminPage.Add('Username:', False);
  AdminPage.Add('Full name:', False);
  AdminPage.Add('Password (min 10 characters):', True);
  AdminPage.Add('Confirm password:', True);
  AdminPage.Values[0] := 'admin';

  // A second, standing backup admin - docs\RECOVERY.md Scenario B calls
  // this the "do this first, always" path and says every FITWORK setup is
  // supposed to have one; the installer previously had no way to create it
  // (RunPostInstallSteps always passed --skip-backup), silently dropping
  // the one piece of enforcement createAdmin.ts's own interactive prompt
  // otherwise provides (strongly-recommended-yes by default). On its own
  // page, not appended to AdminPage above - found live that cramming both
  // accounts' 8 fields onto one CreateInputQueryPage page overflowed the
  // wizard's fixed-height content area with no scrollbar: with the
  // primary fields filled in, the backup admin's full name/password/
  // confirm fields were below the fold and completely unreachable,
  // making the feature unusable through the wizard despite compiling and
  // validating correctly. All four fields here are optional as a group:
  // leave the backup username blank to skip entirely, same as answering
  // "n" to that interactive prompt - see NextButtonClick for the
  // validation this implies.
  BackupAdminPage := CreateInputQueryPage(AdminPage.ID,
    'Create a Backup Admin Account (Optional)',
    'Strongly recommended - see docs\RECOVERY.md, Scenario B.',
    'This is your way back in in case the primary admin''s credentials are ever lost. Leave all four ' +
    'fields below blank to skip this and add one later from Admin > Users instead.');
  BackupAdminPage.Add('Backup admin username:', False);
  BackupAdminPage.Add('Backup admin full name:', False);
  BackupAdminPage.Add('Backup admin password (min 10 characters):', True);
  BackupAdminPage.Add('Confirm backup admin password:', True);
  BackupAdminPage.Values[0] := 'admin2';
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  // Detect lazily, once, the first time the Server Options page is actually
  // shown. This runs during the pre-install wizard, well before [Files] is
  // copied to {app} - DetectLanIpViaApp() deliberately runs against the
  // dontcopy/ExtractTemporaryFile {tmp} copies for exactly this reason, not
  // {app}\..., which doesn't exist yet at this point in the wizard.
  if CurPageID = ServerOptionsPage.ID then
  begin
    if not LanIpDetected then
    begin
      DetectedLanIpCache := DetectLanIpViaApp();
      LanIpDetected := True;
    end;
    // Rebuilt every time this page is (re)entered, not just once like the
    // LAN-IP shell-out above - unlike that detection, GetPort() is free to
    // call repeatedly, and it needs to be: the user can go Back to PortPage,
    // change the port, then Next forward into this page again, and both the
    // checkbox label and the message below must reflect that new value, not
    // whatever was true the first time this page was shown.
    ServerOptionsPage.CheckListBox.Items[0] :=
      'Add a Windows Firewall rule so other PCs can reach this one on port ' + GetPort();
    LanIpLabel.Caption := 'Other PCs will connect at: http://' + DetectedLanIpCache + ':' + GetPort() + #13#10 +
      'Wrong adapter? You can change this later by editing SERVER_MODE and re-running setup, or checking ' +
      'the PC''s network settings directly - this is just a best-effort guess.';
  end;

  if CurPageID = wpFinished then
  begin
    if IsServerMode() then
    begin
      if HttpsConfigured then
        WizardForm.FinishedLabel.Caption := WizardForm.FinishedLabel.Caption + #13#10 + #13#10 +
          'FITWORK is running as a Windows Service and will start automatically on boot.' + #13#10 +
          'Other PCs on this network can connect at: https://' + DetectedLanIpCache + ':' + GetPort() + #13#10 + #13#10 +
          'HTTPS is already set up on this PC. Each OTHER PC or phone that connects will show a one-time ' +
          'browser security warning until it''s told to trust this PC''s certificate - see docs\INSTALL.md ' +
          'for how to copy and install it there.'
      else
        WizardForm.FinishedLabel.Caption := WizardForm.FinishedLabel.Caption + #13#10 + #13#10 +
          'FITWORK is running as a Windows Service and will start automatically on boot.' + #13#10 +
          'Other PCs on this network can connect at: http://' + DetectedLanIpCache + ':' + GetPort() + #13#10 + #13#10 +
          'This is plain HTTP for now - webcam capture will only work from this PC. Automatic HTTPS setup ' +
          'did not complete (see the summary after this) - use the "Regenerate HTTPS Certificate" shortcut ' +
          'in the Start Menu folder to try again, or see docs\INSTALL.md.';
    end
    else
    begin
      WizardForm.FinishedLabel.Caption := WizardForm.FinishedLabel.Caption + #13#10 + #13#10 +
        'FITWORK is running as a Windows Service and will start automatically on boot, available at ' +
        'http://localhost:' + GetPort() + ' on this PC.';
    end;
  end;
end;

// Validates the admin-account page before letting the wizard move past it -
// catches the common mistakes (blank fields, too-short password, mismatched
// confirmation) right there instead of only discovering them later when
// RunPostInstallSteps' createAdmin.js call fails with a generic exit code.
// Mirrors createAdmin.ts's own >= 10 character check; deliberately doesn't
// duplicate its common-password blocklist here too - that failure mode
// still surfaces (just as a less specific "exit code 1") rather than
// keeping two copies of that list in sync.
//
// The four backup-admin fields (indices 4-7) are validated as a group:
// leaving the username blank skips backup-admin creation entirely (same
// meaning as answering "n" to createAdmin.ts's own interactive prompt);
// any other combination - a blank username with something else filled in,
// or a filled-in username with a gap elsewhere - is treated as a mistake
// and blocked, rather than silently discarding whatever was typed.
function NextButtonClick(CurPageID: Integer): Boolean;
var
  BackupProvided: Boolean;
  PortStr: String;
  PortNum: Integer;
begin
  Result := True;
  if CurPageID = PortPage.ID then
  begin
    PortStr := Trim(PortPage.Values[0]);
    // IsAllDigits rejects anything Val used to catch via its error-code
    // output (a leading '-', a trailing non-digit, an empty string) before
    // StrToIntDef ever sees it - StrToIntDef alone would accept some of
    // those silently as a wrong number instead of rejecting them outright,
    // which is exactly what a port field can't afford to do quietly.
    if (not IsAllDigits(PortStr)) then
    begin
      MsgBox('Enter a valid port number between 1 and 65535.', mbError, MB_OK);
      Result := False;
    end
    else
    begin
      PortNum := StrToIntDef(PortStr, 0);
      if (PortNum < 1) or (PortNum > 65535) then
      begin
        MsgBox('Enter a valid port number between 1 and 65535.', mbError, MB_OK);
        Result := False;
      end;
    end;
  end
  else if CurPageID = AdminPage.ID then
  begin
    if Trim(AdminPage.Values[0]) = '' then
    begin
      MsgBox('Enter a username for the admin account.', mbError, MB_OK);
      Result := False;
    end
    else if Trim(AdminPage.Values[1]) = '' then
    begin
      MsgBox('Enter a full name for the admin account.', mbError, MB_OK);
      Result := False;
    end
    else if Length(AdminPage.Values[2]) < 10 then
    begin
      MsgBox('Password must be at least 10 characters long.', mbError, MB_OK);
      Result := False;
    end
    else if AdminPage.Values[2] <> AdminPage.Values[3] then
    begin
      MsgBox('Password and confirmation do not match.', mbError, MB_OK);
      Result := False;
    end;
  end
  else if CurPageID = BackupAdminPage.ID then
  begin
    BackupProvided := (Trim(BackupAdminPage.Values[0]) <> '') or (Trim(BackupAdminPage.Values[1]) <> '') or
      (BackupAdminPage.Values[2] <> '') or (BackupAdminPage.Values[3] <> '');
    if BackupProvided then
    begin
      if Trim(BackupAdminPage.Values[0]) = '' then
      begin
        MsgBox('Enter a username for the backup admin account, or clear all four fields to skip it.', mbError, MB_OK);
        Result := False;
      end
      else if Trim(BackupAdminPage.Values[1]) = '' then
      begin
        MsgBox('Enter a full name for the backup admin account.', mbError, MB_OK);
        Result := False;
      end
      else if Length(BackupAdminPage.Values[2]) < 10 then
      begin
        MsgBox('Backup admin password must be at least 10 characters long.', mbError, MB_OK);
        Result := False;
      end
      else if BackupAdminPage.Values[2] <> BackupAdminPage.Values[3] then
      begin
        MsgBox('Backup admin password and confirmation do not match.', mbError, MB_OK);
        Result := False;
      end
      else if CompareText(BackupAdminPage.Values[0], AdminPage.Values[0]) = 0 then
      begin
        MsgBox('The backup admin must use a different username than the primary admin.', mbError, MB_OK);
        Result := False;
      end;
    end;
  end;
end;

// Inno Setup calls this automatically once, right after the wizard pages
// are done and right before the actual installation (file copy) begins -
// the one hook meant for exactly this: stopping whatever this installer
// is about to overwrite, before Inno tries to touch any of its files.
//
// Found live: running the installer over an existing install without
// uninstalling first died during file extraction with "DeleteFile
// failed; code 5. Access is denied." on vendor\node\node.exe, because the
// previous install's still-running FITWORK service has that exact file
// open. This is the "no guard against installing over an
// already-registered service" item from this file's Known Limitations,
// now a concrete hard failure rather than a hypothetical one. Stopping
// AND removing the old service here (not just stopping it) also means
// RunPostInstallSteps' own `nssm install` always starts from a clean
// slate, rather than nssm's version-dependent no-op-or-error behavior for
// installing over an already-registered service name.
function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  NssmExe: String;
  ResultCode: Integer;
begin
  Result := '';
  NssmExe := ExpandConstant('{app}\vendor\nssm\nssm.exe');
  // Only present at all if a previous install put it there - nothing to
  // stop on a genuinely fresh install. Best-effort otherwise: if the
  // service isn't actually registered, or is already stopped, these just
  // fail harmlessly - this isn't a user-facing failure point, only
  // pre-emptive cleanup before file copy starts.
  if FileExists(NssmExe) then
  begin
    Exec(NssmExe, 'stop {#ServiceName}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    Exec(NssmExe, 'remove {#ServiceName} confirm', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;
end;

// .env is generated here, not shipped as a static [Files] entry, so it
// always reflects what was actually picked in the wizard rather than a
// stale template - see the [Files] section's note on why .env is excluded
// from staging. Runs after files are copied (ssPostInstall) but before
// [Run] fires (migrate deploy needs DATABASE_PATH to already be there).
procedure GenerateEnvFile();
var
  ServerModeValue: String;
  Content: AnsiString;
begin
  if IsServerMode() then
    ServerModeValue := 'server'
  else
    ServerModeValue := 'standalone';

  Content :=
    'DATABASE_PATH=../data/fitwork.db' + #13#10 +
    'PORT=' + GetPort() + #13#10 +
    'NODE_ENV=production' + #13#10 +
    'SERVER_MODE=' + ServerModeValue + #13#10 +
    'SELF_EDIT_WINDOW_MINUTES=15' + #13#10 +
    'SESSION_IDLE_HOURS=8' + #13#10 +
    'SESSION_ABSOLUTE_HOURS=12' + #13#10 +
    'TLS_KEY_PATH=./certs/dev-key.pem' + #13#10 +
    'TLS_CERT_PATH=./certs/dev-cert.pem' + #13#10 +
    'STORAGE_DIR=../storage' + #13#10 +
    'BACKUP_PATH=../data/backups' + #13#10;

  SaveStringToFile(ExpandConstant('{app}\server\.env'), Content, False);
end;

// Runs one external command and checks its exit code - previously every
// database-setup/service-install/service-start step was a declarative
// [Run] entry with no failure handling at all, so a failure anywhere (found
// live: migrate deploy failing P1012 on a missing DATABASE_URL) just fell
// through to every later step running anyway against a broken state, and
// the installer reported success regardless. Critical steps abort the
// whole install immediately via RaiseException, with a message naming the
// step and exit code, rather than leaving a half-configured install that
// LOOKS like it succeeded. Non-critical steps (cosmetic service settings,
// log rotation, optional firewall/power tweaks) instead collect a warning
// shown together at the end, since the service can still function without
// them.
procedure RunStep(const Description, Filename, Params, WorkingDir: String; Critical: Boolean);
var
  ResultCode: Integer;
  Ok: Boolean;
begin
  WizardForm.StatusLabel.Caption := Description;
  Ok := Exec(Filename, Params, WorkingDir, SW_HIDE, ewWaitUntilTerminated, ResultCode) and (ResultCode = 0);
  if not Ok then
  begin
    if Critical then
      RaiseException(Description + ' failed (exit code ' + IntToStr(ResultCode) + '). Setup cannot continue.')
    else
      StepWarnings := StepWarnings + '- ' + Description + ' (exit code ' + IntToStr(ResultCode) + ')' + #13#10;
  end;
end;

// Direct Win32 API imports, used only by RunWithTimeout below. Inno Setup's
// Exec() has no timeout of its own - ewWaitUntilTerminated (what RunStep
// above uses) waits forever, ewNoWait doesn't wait at all - so a real
// timeout needs the raw OS primitives instead: launch with ewNoWait (which
// hands back the new process's PID, not an exit code, in that mode), open
// a handle to it, and wait on that handle with an actual millisecond
// timeout. `external` DLL imports are a documented, long-stable Inno Setup
// Pascal Script feature (see "Support Functions Reference" in the Inno
// Setup help) - not a hack, but still unverified here like everything else
// in this file, since there's no Windows machine to compile this against.
const
  SYNCHRONIZE = $00100000;
  PROCESS_QUERY_INFORMATION = $0400;
  PROCESS_TERMINATE = $0001;
  WAIT_OBJECT_0 = 0;

function OpenProcess(dwDesiredAccess: LongWord; bInheritHandle: LongBool; dwProcessId: LongWord): LongWord;
  external 'OpenProcess@kernel32.dll stdcall';
function WaitForSingleObject(hHandle: LongWord; dwMilliseconds: LongWord): LongWord;
  external 'WaitForSingleObject@kernel32.dll stdcall';
function GetExitCodeProcess(hProcess: LongWord; var lpExitCode: LongWord): LongBool;
  external 'GetExitCodeProcess@kernel32.dll stdcall';
function TerminateProcess(hProcess: LongWord; uExitCode: LongWord): LongBool;
  external 'TerminateProcess@kernel32.dll stdcall';
function CloseHandle(hObject: LongWord): LongBool;
  external 'CloseHandle@kernel32.dll stdcall';

// Runs Filename/Params with a hard wall-clock timeout, unlike RunStep's
// indefinite wait - used only for the two mkcert.exe calls in
// SetupHttpsForServerMode below, where whether mkcert.exe -install truly
// runs headless when launched from an already-elevated, unattended
// installer process (no interactive desktop session for any unexpected
// prompt to be shown on, or is there one? - not something confirmable
// without a real Windows box) is exactly the kind of failure mode an
// indefinite wait turns into a permanently hung install. On timeout,
// TerminateProcess kills it rather than leaving an orphaned process behind
// - ResultCode comes back as -2 specifically so callers can tell "timed
// out" apart from an ordinary nonzero exit code.
function RunWithTimeout(const Filename, Params, WorkingDir: String; TimeoutMs: LongWord; var ResultCode: Integer): Boolean;
var
  Pid: Integer;
  ProcHandle: LongWord;
  WaitResult: LongWord;
  ExitCodeW: LongWord;
begin
  Result := False;
  ResultCode := -1;
  if not Exec(Filename, Params, WorkingDir, SW_HIDE, ewNoWait, Pid) then
    Exit;

  ProcHandle := OpenProcess(SYNCHRONIZE or PROCESS_QUERY_INFORMATION or PROCESS_TERMINATE, False, Pid);
  if ProcHandle = 0 then
    Exit;

  try
    WaitResult := WaitForSingleObject(ProcHandle, TimeoutMs);
    if WaitResult = WAIT_OBJECT_0 then
    begin
      GetExitCodeProcess(ProcHandle, ExitCodeW);
      ResultCode := ExitCodeW;
      Result := True;
    end
    else
    begin
      // Timed out (or the wait call itself failed) - kill it rather than
      // leave an unattended install with an orphaned process still running.
      TerminateProcess(ProcHandle, 1);
      ResultCode := -2;
    end;
  finally
    CloseHandle(ProcHandle);
  end;
end;

// Exec() can't capture a launched process's stdout/stderr directly - same
// cmd.exe-redirect-to-a-temp-file workaround as DetectLanIpViaApp above.
// Only used for the recovery-key step below, which has a fixed, hardcoded
// command line with no user-supplied content at all (no password, nothing
// that could contain a cmd.exe metacharacter like % or & or | and corrupt
// or break out of this) - deliberately NOT used for createAdmin.js, whose
// Params contains the operator's own chosen password verbatim: routing
// that through cmd.exe's shell parsing would risk exactly that kind of
// corruption for a password containing those characters, whereas the
// plain Exec() RunStep already uses goes straight to CreateProcess with no
// shell interpretation in between at all.
function RunAndCaptureOutput(const Filename, Params: String; var ResultCode: Integer): String;
var
  OutFile: String;
  Output: AnsiString;
begin
  // Fixed filename, no uniqueness suffix - {tmp} is already a fresh,
  // unique-per-install directory on its own (confirmed: GetTickCount is
  // not a real Inno Setup Pascal Script identifier, ISCC rejected it
  // outright), and every caller fully writes, reads, and deletes this
  // file before returning, with no concurrent use of it in between.
  Result := '';
  OutFile := ExpandConstant('{tmp}\fitwork-output.txt');
  Exec(ExpandConstant('{cmd}'),
    '/C ""' + Filename + '" ' + Params + ' > "' + OutFile + '" 2>&1"',
    '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  if LoadStringFromFile(OutFile, Output) then
    Result := Trim(String(Output));
  DeleteFile(OutFile);
end;

// Everything that used to be declarative [Run] entries - see that section's
// note. Runs from CurStepChanged(ssPostInstall), right after .env is
// generated, so it's still on the same visible "Installing..." wizard page
// StatusMsg: used to update automatically for declarative entries -
// RunStep updates WizardForm.StatusLabel.Caption itself to preserve that.
// Escapes \ and " for embedding a value inside a JSON string literal -
// order matters: backslashes must be doubled BEFORE quotes are escaped, or
// the backslash just inserted to escape a quote would itself get doubled
// by a backslash pass that runs after it.
function JsonEscape(const S: String): String;
begin
  Result := S;
  StringChangeEx(Result, '\', '\\', False);
  StringChangeEx(Result, '"', '\"', False);
end;

// Automatic HTTPS for Server-mode installs, using the bundled mkcert.exe
// (staged by build.ps1 the same way nssm.exe already is) instead of
// requiring the admin to separately download and install mkcert first, or
// remembering to double-click Setup-HTTPS.bat afterwards - that manual
// tool still exists (retitled "Regenerate HTTPS Certificate" in [Icons])
// for later use, e.g. after a DHCP-reassigned LAN IP, but first-install
// setup no longer depends on it. Standalone mode skips this entirely -
// nothing else on the network reaches that machine, so there's no browser-
// trust problem for it to solve. Runs BEFORE nssm start (see
// RunPostInstallSteps below) so the very first launch already comes up on
// HTTPS, rather than needing the restart-the-service step the manual tool
// requires. Every failure here is non-critical - added to StepWarnings,
// same as the firewall/power steps - since the app runs fine over plain
// HTTP; this only affects whether webcam capture works from other PCs.
procedure SetupHttpsForServerMode();
var
  MkcertExe, CertsDir, KeyPath, CertPath, Hosts: String;
  ResultCode: Integer;
begin
  HttpsConfigured := False;
  if not IsServerMode() then
    Exit;

  MkcertExe := ExpandConstant('{app}\vendor\mkcert\mkcert.exe');
  if not FileExists(MkcertExe) then
  begin
    StepWarnings := StepWarnings +
      '- Setting up HTTPS (mkcert.exe missing from this install) - see docs\INSTALL.md to set it up manually' + #13#10;
    Exit;
  end;

  CertsDir := ExpandConstant('{app}\server\certs');
  ForceDirectories(CertsDir);
  // Matches config.tlsKeyPath/tlsCertPath's defaults (./certs/dev-key.pem,
  // ./certs/dev-cert.pem relative to the server directory) - see
  // GenerateEnvFile above - so the running app picks these up with no
  // additional .env change needed.
  KeyPath := CertsDir + '\dev-key.pem';
  CertPath := CertsDir + '\dev-cert.pem';

  // Same DetectedLanIpCache the wizard's own on-screen LAN-IP message
  // already uses (see CurPageChanged) - one detection, shown and used
  // consistently, rather than a second independent call that could
  // theoretically disagree with what the admin was told during setup.
  Hosts := 'localhost 127.0.0.1';
  if (DetectedLanIpCache <> '') and (Pos('unknown', DetectedLanIpCache) = 0) then
    Hosts := Hosts + ' ' + DetectedLanIpCache;

  WizardForm.StatusLabel.Caption := 'Setting up HTTPS...';

  // 30s is generous for what's normally a sub-second operation on both
  // calls - long enough that a slow/loaded PC doesn't get killed for
  // legitimately still working, short enough that an unattended install
  // isn't stuck for minutes if this does hang on something unexpected.
  if not (RunWithTimeout(MkcertExe, '-install', '', 30000, ResultCode) and (ResultCode = 0)) then
  begin
    if ResultCode = -2 then
      StepWarnings := StepWarnings +
        '- Installing the HTTPS certificate authority (timed out after 30s, so it was stopped) - see docs\INSTALL.md to set up HTTPS manually' + #13#10
    else
      StepWarnings := StepWarnings +
        '- Installing the HTTPS certificate authority (exit code ' + IntToStr(ResultCode) + ') - see docs\INSTALL.md to set up HTTPS manually' + #13#10;
    Exit;
  end;

  if not (RunWithTimeout(MkcertExe,
     '-key-file "' + KeyPath + '" -cert-file "' + CertPath + '" ' + Hosts, '', 30000, ResultCode) and (ResultCode = 0)) then
  begin
    if ResultCode = -2 then
      StepWarnings := StepWarnings +
        '- Generating the HTTPS certificate (timed out after 30s, so it was stopped) - see docs\INSTALL.md to set up HTTPS manually' + #13#10
    else
      StepWarnings := StepWarnings +
        '- Generating the HTTPS certificate (exit code ' + IntToStr(ResultCode) + ') - see docs\INSTALL.md to set up HTTPS manually' + #13#10;
    Exit;
  end;

  HttpsConfigured := True;
end;

procedure RunPostInstallSteps();
var
  NssmExe, NodeExe, PrismaCli, EnvPreload, AppDir, CreateAdminJs, RecoveryToolJs, RecoveryKey, AdminInputFile, AdminJson: String;
  RecoveryKeyResultCode: Integer;
  BackupAdminProvided: Boolean;
begin
  NssmExe := ExpandConstant('{app}\vendor\nssm\nssm.exe');
  NodeExe := ExpandConstant('{app}\vendor\node\node.exe');
  PrismaCli := ExpandConstant('{app}\server\node_modules\prisma\build\index.js');
  EnvPreload := ExpandConstant('{app}\server\dist\env.js');
  AppDir := ExpandConstant('{app}\server');
  CreateAdminJs := ExpandConstant('{app}\server\dist\cli\createAdmin.js');
  RecoveryToolJs := ExpandConstant('{app}\server\dist\cli\recoveryTool.js');

  // -r preloads env.js in the same process, before Prisma's CLI runs -
  // env.js (server/src/env.ts) is what computes DATABASE_URL from the
  // friendlier DATABASE_PATH for the app's own normal startup, and
  // schema.prisma only understands DATABASE_URL. Invoking Prisma's CLI
  // directly like this has no other way to pick that translation up.
  // Found live: without this, .env has DATABASE_PATH but no DATABASE_URL
  // at all, and migrate deploy failed validation (P1012) before touching
  // the filesystem. Deliberately not also writing DATABASE_URL into .env
  // instead - two variables naming the same file drift the moment only one
  // of them gets updated by hand later.
  RunStep('Setting up the database...', NodeExe,
    '-r "' + EnvPreload + '" "' + PrismaCli + '" migrate deploy', AppDir, True);

  // Creates the account(s) collected on the admin-credentials wizard page
  // (see InitializeWizard/NextButtonClick) - must run after migrate deploy
  // (the Users table doesn't exist before that) but can otherwise go
  // anywhere before the service actually starts. Critical - without at
  // least the primary account nobody can ever log in, which is exactly
  // the failure mode this whole step exists to prevent. The backup admin
  // (fields 4-7, optional as a group - NextButtonClick already confirmed
  // they're either all blank or all valid) is included in the same JSON
  // and the same createAdmin.js call when provided, omitting --skip-backup
  // in that case - createAdmin.ts already knows what to do with
  // backupUsername/backupFullName/backupPassword together.
  //
  // Credentials go via a temporary JSON file (--input-file, read once and
  // never re-read) rather than --username/--fullName/--password/etc. on
  // the command line: a plain argv password sits in this process's own
  // command line for the life of the call, visible to any other user on
  // the machine via Task Manager/tasklist/Process Explorer with no special
  // privilege needed - a real concern on a shared clinic PC. Inno Setup's
  // Exec() has no stdin-piping option, which would avoid even the brief
  // on-disk file, so this is the closest available equivalent; the file
  // lives under {tmp} and is deleted immediately after, success or
  // failure (see the try/finally - RunStep's RaiseException on a critical
  // failure would otherwise skip a DeleteFile placed after it, leaking the
  // file). Still plain Exec(), not routed through cmd.exe like the
  // recovery-key step below - see RunAndCaptureOutput's own comment for
  // why that would be a different, additional risk here.
  // Fixed filename, same reasoning as RunAndCaptureOutput's OutFile above -
  // {tmp} is already unique per install, and this file is written, read
  // by createAdmin.js, and deleted (see the try/finally below) once, with
  // nothing else touching it in between.
  // Skipped entirely on top of the wizard already not asking for these
  // details (see ShouldSkipPage) - belt and suspenders, since
  // RunPostInstallSteps is the one place that actually matters: an
  // existing database means an admin account already exists, and calling
  // createAdmin.js anyway hit a unique-constraint violation and aborted
  // the whole install (#19) - confirmed live against a reinstall over an
  // existing, non-uninstalled install (AdminPage.Values would have been
  // blank in that case anyway, since the pages were skipped, which would
  // have failed username validation in createAdmin.js in its own right).
  if not ExistingDatabaseFound() then
  begin
    AdminInputFile := ExpandConstant('{tmp}\fitwork-admin-input.json');
    AdminJson :=
      '{"username":"' + JsonEscape(AdminPage.Values[0]) + '","fullName":"' + JsonEscape(AdminPage.Values[1]) +
      '","password":"' + JsonEscape(AdminPage.Values[2]) + '"';
    BackupAdminProvided := Trim(BackupAdminPage.Values[0]) <> '';
    if BackupAdminProvided then
      AdminJson := AdminJson +
        ',"backupUsername":"' + JsonEscape(BackupAdminPage.Values[0]) + '","backupFullName":"' + JsonEscape(BackupAdminPage.Values[1]) +
        '","backupPassword":"' + JsonEscape(BackupAdminPage.Values[2]) + '"';
    AdminJson := AdminJson + '}';
    SaveStringToFile(AdminInputFile, AdminJson, False);
    try
      if BackupAdminProvided then
        RunStep('Creating your admin accounts...', NodeExe,
          '"' + CreateAdminJs + '" --input-file "' + AdminInputFile + '"', AppDir, True)
      else
        RunStep('Creating your admin account...', NodeExe,
          '"' + CreateAdminJs + '" --input-file "' + AdminInputFile + '" --skip-backup', AppDir, True);
    finally
      DeleteFile(AdminInputFile);
    end;
  end;

  // Generates the recovery key (see docs/RECOVERY.md) right now, during
  // install, rather than leaving it to whether the operator remembers to
  // separately double-click Recovery-Tool.bat afterwards - found live that
  // the installer previously shipped no way to generate this at all
  // (same root cause as the admin account above: no scripts\, no tsx).
  // --print-key-if-new is safe to call unconditionally, including on a
  // repeat install over an existing database: it only ever generates once,
  // gated on whether a recovery_key_hash row already exists, and never
  // regenerates - so never silently invalidates - a key from an earlier
  // install. Prints nothing on a repeat install, in which case there's
  // nothing new to show and this step is silently a no-op.
  RecoveryKey := RunAndCaptureOutput(NodeExe,
    '"' + RecoveryToolJs + '" --print-key-if-new', RecoveryKeyResultCode);
  if RecoveryKeyResultCode <> 0 then
    StepWarnings := StepWarnings +
      '- Generating the recovery key (exit code ' + IntToStr(RecoveryKeyResultCode) +
      ') - see docs\RECOVERY.md to generate one manually via Recovery-Tool.bat' + #13#10
  else if RecoveryKey <> '' then
    MsgBox(
      'IMPORTANT - Recovery key generated' + #13#10#13#10 +
      'Write this down and store it somewhere safe OFFLINE (printed, filed by IT/management - never saved ' +
      'as a file on this computer). If every admin account is ever locked out, this key is the only way ' +
      'back in - see docs\RECOVERY.md.' + #13#10#13#10 +
      'This is the ONLY time this key will ever be shown:' + #13#10#13#10 +
      RecoveryKey,
      mbInformation, MB_OK);

  // Defensive, not decorative: found live that uninstalling with the
  // data-deletion prompt answered Yes did NOT actually clear
  // server\logs\ despite CurUninstallStepChanged's own DelTree call for
  // it (added earlier this round) - the reinstalled service's
  // service-out.log carried a fresh today's-date timestamp but still
  // contained startup banner lines from two installs ago, meaning
  // something wrote fresh content on top of old content that was never
  // actually removed. Root cause unconfirmed (nssm/the just-stopped
  // service holding the file handle a moment longer than the uninstaller
  // waits for is the leading theory) - rather than chase that further,
  // guarantee a clean log directory at the one point in this whole
  // lifecycle where nothing could possibly still have it open: right here,
  // before this install's own nssm install/start even creates the
  // service, let alone starts writing to it.
  DelTree(ExpandConstant('{app}\server\logs'), True, True, True);
  // Found live (this DelTree's own regression): [Dirs] only creates
  // server\logs during the file-copy phase, which already happened by the
  // time ssPostInstall (and this whole procedure) runs - deleting it here
  // with nothing after it to recreate the directory left nssm with
  // nowhere to write AppStdout/AppStderr, so the service ran but logged
  // nothing at all, silently. ForceDirectories recreates exactly what
  // DelTree just removed, before nssm (which does not create missing
  // directories for its own log files) is ever configured to write there.
  ForceDirectories(ExpandConstant('{app}\server\logs'));

  // Before the service is installed/started below, so a Server-mode
  // install's very first launch already comes up on HTTPS - see
  // SetupHttpsForServerMode's own comment for why. No-op (HttpsConfigured
  // just stays False) for Standalone mode.
  SetupHttpsForServerMode();

  // AppParameters is set to the RELATIVE path "dist\index.js", not an
  // absolute "{app}\server\dist\index.js" - found live (twice) that this is
  // the only way to get this value to nssm intact. AppParameters is passed
  // to CreateProcess as part of the full command line and re-split by
  // CommandLineToArgvW when the service actually launches - a cleanly
  // stored absolute path containing a space still breaks at that point,
  // confirmed via `nssm get FITWORK AppParameters` returning the full path
  // correctly while the service still crashed with "Cannot find module
  // 'C:\Program'". Application/AppDirectory below are never affected by
  // this, not because of how they're set, but because they map to
  // CreateProcess's lpApplicationName/lpCurrentDirectory - discrete
  // parameters that never go through command-line splitting at all. A
  // relative path has no space-splitting risk to begin with, and resolves
  // correctly against AppDirectory regardless of where {app} ends up.
  RunStep('Installing FITWORK service...', NssmExe,
    'install {#ServiceName} "' + NodeExe + '"', '', True);
  RunStep('Configuring FITWORK service...', NssmExe,
    'set {#ServiceName} AppParameters dist\index.js', '', True);
  RunStep('Configuring FITWORK service...', NssmExe,
    'set {#ServiceName} AppDirectory "' + AppDir + '"', '', True);
  RunStep('Configuring FITWORK service...', NssmExe,
    'set {#ServiceName} DisplayName "FITWORK EMR"', '', False);
  RunStep('Configuring FITWORK service...', NssmExe,
    'set {#ServiceName} Description "FITWORK electronic medical records server"', '', False);
  RunStep('Configuring FITWORK service...', NssmExe,
    'set {#ServiceName} Start SERVICE_AUTO_START', '', True);
  RunStep('Configuring FITWORK service...', NssmExe,
    'set {#ServiceName} AppStdout "' + ExpandConstant('{app}\server\logs\service-out.log') + '"', '', False);
  RunStep('Configuring FITWORK service...', NssmExe,
    'set {#ServiceName} AppStderr "' + ExpandConstant('{app}\server\logs\service-err.log') + '"', '', False);
  RunStep('Configuring FITWORK service...', NssmExe,
    'set {#ServiceName} AppRotateFiles 1', '', False);
  RunStep('Configuring FITWORK service...', NssmExe,
    'set {#ServiceName} AppRotateBytes 10485760', '', False);

  // Both opt-out (checked by default, see ShouldAddFirewallRule/
  // ShouldDisableSleep) and only apply in Server mode - non-critical, since
  // the admin can add these manually and the service runs fine without
  // them either way.
  if ShouldAddFirewallRule() then
    RunStep('Adding firewall rule...', ExpandConstant('{sys}\netsh.exe'),
      'advfirewall firewall add rule name="{#AppName}" dir=in action=allow protocol=TCP localport=' + GetPort(),
      '', False);
  if ShouldDisableSleep() then
  begin
    RunStep('Adjusting power settings...', ExpandConstant('{sys}\powercfg.exe'), '/change standby-timeout-ac 0', '', False);
    RunStep('Adjusting power settings...', ExpandConstant('{sys}\powercfg.exe'), '/change standby-timeout-dc 0', '', False);
    RunStep('Adjusting power settings...', ExpandConstant('{sys}\powercfg.exe'), '/hibernate off', '', False);
  end;

  // Started last, once the database, service config, and any firewall/
  // power changes are all in place. Critical - if this fails the install
  // has completed but nothing is actually running, which the user needs to
  // know now rather than discovering it themselves at http://localhost.
  RunStep('Starting FITWORK...', NssmExe, 'start {#ServiceName}', '', True);

  if StepWarnings <> '' then
    MsgBox('FITWORK is installed and running, but a few optional steps did not complete:' + #13#10#13#10 +
      StepWarnings + #13#10 +
      'None of these affect whether the service runs - they cover things like the service''s display ' +
      'name, log file rotation, the firewall rule, or power settings. You can redo any of them manually ' +
      'later if needed (see docs\INSTALL.md).',
      mbInformation, MB_OK);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    GenerateEnvFile();
    RunPostInstallSteps();
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  DeleteData: Integer;
begin
  // [UninstallRun]'s service-stop/remove entries have already run by this
  // point (usPostUninstall comes after the "run programs" phase) - this
  // only decides whether clinical data itself gets deleted, never silently.
  if CurUninstallStep = usPostUninstall then
  begin
    DeleteData := MsgBox(
      'Do you also want to permanently delete the FITWORK database, backups, and logs?' + #13#10 + #13#10 +
      'This includes every employee record, clinical note, every backup ever made, and the service''s log ' +
      'files. This cannot be undone.' + #13#10 + #13#10 +
      'Choose No to keep this data - you can reinstall FITWORK later and it will still be there.',
      mbConfirmation, MB_YESNO or MB_DEFBUTTON2);

    if DeleteData = IDYES then
    begin
      DelTree(ExpandConstant('{app}\data'), True, True, True);
      DelTree(ExpandConstant('{app}\storage'), True, True, True);
      // Found live: uninstalling (even choosing Yes here) never removed
      // server\logs, so service-out.log/service-err.log accumulated lines
      // across every install/uninstall/reinstall cycle indefinitely - not
      // itself clinical data, but grouped with the Yes answer since a
      // restart's error output can echo operational details (paths,
      // usernames) that "delete my data" should reasonably also clear.
      DelTree(ExpandConstant('{app}\server\logs'), True, True, True);
    end;
  end;
end;
