import ExcelJS from "exceljs";
import { Response } from "express";

// Data-only counterpart to reportDocx.ts's Word builder — same reports,
// same query layer and scope, but strictly headers + rows, never narrative
// text or charts (Word stays the only format with those). One sheet per
// section for multi-section reports (Comprehensive-style), a single data
// sheet for Summary/Detailed-style reports — either way, a "Metadata" sheet
// always comes first with report type, scope, year(s)/period, and
// generated-by/date, so the numbers are never separated from the context
// they were pulled under.
export interface ReportMetadata {
  reportType: string;
  scopeLabel: string;
  period: string; // e.g. "2026" or "2025 vs 2026" or "2026-01-01 to 2026-06-30"
  generatedBy: string;
  generatedAt: Date;
}

export function createReportWorkbook(meta: ReportMetadata): ExcelJS.Workbook {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = meta.generatedBy;
  workbook.created = meta.generatedAt;

  const sheet = workbook.addWorksheet("Metadata");
  sheet.columns = [{ width: 20 }, { width: 50 }];
  const rows: [string, string][] = [
    ["Report type", meta.reportType],
    ["Scope", meta.scopeLabel],
    ["Period", meta.period],
    ["Generated by", meta.generatedBy],
    ["Generated at", meta.generatedAt.toLocaleString()],
  ];
  for (const [label, value] of rows) {
    const row = sheet.addRow([label, value]);
    row.getCell(1).font = { bold: true };
  }
  return workbook;
}

// Adds one data sheet: a bold header row followed by plain data rows. Sheet
// names are truncated/sanitized to Excel's 31-char, no-special-character
// limit so a section title like "Illness/Complaint by Department" doesn't
// break sheet creation.
export function addDataSheet(workbook: ExcelJS.Workbook, sheetName: string, headers: string[], rows: (string | number)[][]): ExcelJS.Worksheet {
  const safeName = sheetName.replace(/[*?:\\/[\]]/g, "").slice(0, 31) || "Data";
  const sheet = workbook.addWorksheet(safeName);
  sheet.columns = headers.map((h) => ({ header: h, width: Math.max(12, Math.min(40, h.length + 4)) }));
  const headerRow = sheet.getRow(1);
  headerRow.font = { bold: true };
  headerRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE5EDFB" } };
  for (const r of rows) sheet.addRow(r);
  return sheet;
}

export async function sendXlsx(res: Response, filename: string, workbook: ExcelJS.Workbook): Promise<void> {
  res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
  await workbook.xlsx.write(res);
  res.end();
}
