import {
  Paragraph, Table, TextRun, ImageRun, PageBreak, AlignmentType,
} from "docx";
import { AppBranding, sectionHeading, subHeading, emptyMessage, dataTable } from "../reportDocx";
import {
  ApeComprehensiveStats, ComponentStat, DemographicBreakdown, YearOverYearComponent,
  CompanyBreakdown, FollowUpItem, CompletenessRow,
} from "./stats";
import {
  componentNarrative, demographicNarrative, executiveSummaryNarrative,
  yoyComponentNarrative, companyBreakdownNarrative, methodologyNarrative, pct,
} from "./narrative";
import { renderBarChart, renderGroupedBarChart, ChartBranding, DEFAULT_CHART_BRANDING } from "./charts";
import { CLASSIFIED_COMPONENT_KEYS } from "./classification";

export interface ApeComprehensiveDocOptions {
  branding: AppBranding;
  chartBranding: ChartBranding;
  scopeLabel: string;
  department?: string;
  year: number;
  compareYears: number;
  generatedByFullName: string;
  stats: ApeComprehensiveStats;
  yoyComponents: YearOverYearComponent[];
  companyBreakdown: CompanyBreakdown[] | null;
}

// Global figure counter — one docBuilder run corresponds to one document,
// so a module-level counter would leak across concurrent requests; kept as
// part of the builder's local closure state instead (see buildDoc below).
function makeFigureCounter() {
  let n = 0;
  return () => ++n;
}

function titlePage(opts: ApeComprehensiveDocOptions): Paragraph[] {
  const paragraphs: Paragraph[] = [];
  if (opts.branding.logoBuffer) {
    paragraphs.push(new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 800 },
      children: [new ImageRun({ data: opts.branding.logoBuffer, transformation: { width: 96, height: 96 }, type: "png" })],
    }));
  }
  paragraphs.push(new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { before: 400 },
    children: [new TextRun({ text: opts.branding.appName, bold: true, size: 40 })],
  }));
  paragraphs.push(new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { before: 200, after: 400 },
    children: [new TextRun({ text: "Annual Physical Exam — Comprehensive Report", bold: true, size: 30 })],
  }));
  const lines = [
    `Reporting period: Exam year ${opts.year}${opts.compareYears > 0 ? ` (compared against ${opts.compareYears} prior year${opts.compareYears > 1 ? "s" : ""})` : ""}`,
    `Scope: ${opts.scopeLabel}`,
    `Department: ${opts.department || "All departments"}`,
    `Date generated: ${new Date().toLocaleString()}`,
    `Generated by: ${opts.generatedByFullName}`,
  ];
  for (const line of lines) {
    paragraphs.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 80 }, children: [new TextRun({ text: line, size: 22 })] }));
  }

  paragraphs.push(new Paragraph({ spacing: { before: 1200 }, children: [new TextRun({ text: "Prepared by: ______________________________     Date: ____________", size: 22 })] }));
  paragraphs.push(new Paragraph({ spacing: { before: 400 }, children: [new TextRun({ text: "Reviewed by: ______________________________     Date: ____________", size: 22 })] }));
  paragraphs.push(new Paragraph({ children: [new PageBreak()] }));
  return paragraphs;
}

function chartParagraph(png: Buffer | null, caption: string): Paragraph[] {
  if (!png) return [];
  return [
    new Paragraph({
      alignment: AlignmentType.CENTER, spacing: { before: 120, after: 80 },
      children: [new ImageRun({ data: png, transformation: { width: 465, height: 270 }, type: "png" })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER, spacing: { after: 160 },
      children: [new TextRun({ text: caption, italics: true, size: 18, color: "555555" })],
    }),
  ];
}

function componentTable(stat: ComponentStat): Table | null {
  if (stat.recordedCount === 0) return null;
  const rows = stat.tally.map((t) => [t.label, String(t.count), pct(t.count, stat.recordedCount)]);
  return dataTable(["Classification", "Count", "% of recorded"], rows);
}

function followUpsTable(items: FollowUpItem[]): Table {
  return dataTable(
    ["Employee", "Code", "Urgency", "Reason"],
    items.map((f) => [f.employeeName, f.employeeCode, f.urgency, f.reason]),
  );
}

function componentSection(
  stat: ComponentStat, nextFigure: () => number, chartBranding: ChartBranding, followUps: FollowUpItem[],
): (Paragraph | Table)[] {
  const children: (Paragraph | Table)[] = [subHeading(stat.label)];
  children.push(new Paragraph({ spacing: { after: 120 }, children: [new TextRun({ text: componentNarrative(stat) })] }));

  if (stat.recordedCount > 0 && stat.tally.length > 0) {
    const chart = renderBarChart(stat.label, stat.tally, chartBranding);
    if (chart) {
      const figNum = nextFigure();
      children.push(...chartParagraph(chart.buffer, `Figure ${figNum}: ${stat.label} — distribution of recorded values`));
    }
    const table = componentTable(stat);
    if (table) children.push(table);
  }

  const sectionFollowUps = followUps.filter((f) => f.componentKey === stat.key);
  if (sectionFollowUps.length > 0) {
    children.push(new Paragraph({ spacing: { before: 120 }, children: [new TextRun({ text: "Follow-up items from this section:", bold: true, size: 20 })] }));
    children.push(followUpsTable(sectionFollowUps));
  }

  return children;
}

function demographicSection(breakdown: DemographicBreakdown, nextFigure: () => number, chartBranding: ChartBranding): (Paragraph | Table)[] {
  const children: (Paragraph | Table)[] = [subHeading(breakdown.label)];
  children.push(new Paragraph({ spacing: { after: 120 }, children: [new TextRun({ text: demographicNarrative(breakdown) })] }));
  if (breakdown.tally.length > 0) {
    const chart = renderBarChart(breakdown.label, breakdown.tally, chartBranding);
    if (chart) {
      const figNum = nextFigure();
      children.push(...chartParagraph(chart.buffer, `Figure ${figNum}: ${breakdown.label} distribution`));
    }
    children.push(dataTable(["Group", "Count"], breakdown.tally.map((t) => [t.label, String(t.count)])));
  }
  return children;
}

function completenessTable(rows: CompletenessRow[]): Table {
  return dataTable(["Field", "Recorded", "Missing"], rows.map((r) => [r.field, String(r.recorded), String(r.missing)]));
}

export function buildApeComprehensiveDoc(opts: ApeComprehensiveDocOptions): (Paragraph | Table)[] {
  const nextFigure = makeFigureCounter();
  const chartBranding = opts.chartBranding;
  const children: (Paragraph | Table)[] = [];

  // 1. Title page
  children.push(...titlePage(opts));

  // 2. Executive Summary
  children.push(sectionHeading("Executive Summary"));
  for (const p of executiveSummaryNarrative(opts.stats, opts.scopeLabel)) {
    children.push(new Paragraph({ spacing: { after: 120 }, children: [new TextRun({ text: p })] }));
  }

  // 3. Scope and Methodology
  children.push(sectionHeading("Scope and Methodology"));
  children.push(new Paragraph({ spacing: { after: 120 }, children: [new TextRun({ text: methodologyNarrative(opts.stats, opts.scopeLabel, opts.department) })] }));
  if (opts.stats.examined > 0) {
    for (const c of opts.stats.components) {
      const line = c.totalExamined === 0
        ? `${c.label}: not applicable (no employees examined).`
        : `${c.label}: recorded for ${c.recordedCount} of ${c.totalExamined} examined (${pct(c.recordedCount, c.totalExamined)}).`;
      children.push(new Paragraph({ spacing: { after: 40 }, children: [new TextRun({ text: line, size: 20 })] }));
    }
  }

  // 4. Demographic Profile
  children.push(sectionHeading("Demographic Profile"));
  if (opts.stats.headcount === 0) {
    children.push(emptyMessage("No employees fall under this scope."));
  } else {
    for (const breakdown of opts.stats.demographics) {
      children.push(...demographicSection(breakdown, nextFigure, chartBranding));
    }
  }

  // 5. Per-APE-component sections
  children.push(sectionHeading("Examination Findings by Component"));
  if (opts.stats.examined === 0) {
    children.push(emptyMessage("No employees were examined under this scope for this period."));
  } else {
    for (const stat of opts.stats.components) {
      children.push(...componentSection(stat, nextFigure, chartBranding, opts.stats.followUps));
    }
    // Dental cross-reference — denominator is scope headcount, not examined
    // count (see stats.ts's buildDentalStat comment); called out here too
    // so a reader doesn't assume it's gated the same way as the exam-based
    // components above it.
    children.push(subHeading(opts.stats.dental.label));
    children.push(new Paragraph({
      spacing: { after: 80 },
      children: [new TextRun({ text: "Cross-referenced against the current dental chart, independent of APE exam completion — every employee in scope has a defined state.", italics: true, size: 18, color: "555555" })],
    }));
    children.push(new Paragraph({ spacing: { after: 120 }, children: [new TextRun({ text: componentNarrative(opts.stats.dental) })] }));
    if (opts.stats.dental.tally.length > 0) {
      const chart = renderBarChart(opts.stats.dental.label, opts.stats.dental.tally, chartBranding);
      if (chart) children.push(...chartParagraph(chart.buffer, `Figure ${nextFigure()}: ${opts.stats.dental.label}`));
      const table = componentTable(opts.stats.dental);
      if (table) children.push(table);
    }
  }

  // 6. Year-over-Year Comparison
  children.push(sectionHeading("Year-over-Year Comparison"));
  if (opts.compareYears === 0) {
    children.push(emptyMessage("No prior-year comparison was requested for this report."));
  } else if (opts.yoyComponents.length === 0) {
    children.push(emptyMessage("No components had data to compare."));
  } else {
    for (const comp of opts.yoyComponents) {
      children.push(subHeading(comp.label));
      children.push(new Paragraph({ spacing: { after: 120 }, children: [new TextRun({ text: yoyComponentNarrative(comp) })] }));
      const years = comp.years.map((y) => y.year);
      const seriesLabels = Array.from(new Set(comp.years.flatMap((y) => y.tally.map((t) => t.label))));
      if (seriesLabels.length > 0 && comp.years.some((y) => y.recordedCount > 0)) {
        const series = seriesLabels.map((label) => ({
          label,
          counts: comp.years.map((y) => y.tally.find((t) => t.label === label)?.count ?? 0),
        }));
        const chart = renderGroupedBarChart(comp.label, years, series, chartBranding);
        if (chart) children.push(...chartParagraph(chart.buffer, `Figure ${nextFigure()}: ${comp.label} — ${years.join(" vs ")}`));
      }
    }
  }

  // 7. Findings Requiring Follow-Up
  children.push(sectionHeading("Findings Requiring Follow-Up"));
  if (opts.stats.followUps.length === 0) {
    children.push(emptyMessage("No findings were flagged for follow-up review this period."));
  } else {
    for (const urgency of ["High", "Medium", "Low"] as const) {
      const group = opts.stats.followUps.filter((f) => f.urgency === urgency);
      if (group.length === 0) continue;
      children.push(subHeading(`${urgency} Urgency (${group.length})`));
      children.push(followUpsTable(group));
    }
  }

  // 8. Recommendations (editable draft — never auto-finalized medical advice)
  children.push(sectionHeading("Recommendations"));
  children.push(new Paragraph({
    spacing: { after: 120 },
    children: [new TextRun({ text: "DRAFT — this section is template-generated from the findings above and must be reviewed and edited by a qualified clinician before this report is finalized.", bold: true, italics: true, color: "B45309" })],
  }));
  const recommendationLines = buildDraftRecommendations(opts.stats);
  if (recommendationLines.length === 0) {
    children.push(emptyMessage("No template recommendations were generated — no components had findings meeting the threshold for a suggested action."));
  } else {
    for (const line of recommendationLines) {
      children.push(new Paragraph({ spacing: { after: 80 }, bullet: { level: 0 }, children: [new TextRun({ text: line })] }));
    }
  }

  // 9. Appendix — data completeness
  children.push(sectionHeading("Appendix: Data Completeness"));
  children.push(new Paragraph({
    spacing: { after: 120 },
    children: [new TextRun({ text: "Recorded vs. missing counts per field, over the employees examined this period (not the full scope headcount).", italics: true, size: 18, color: "555555" })],
  }));
  if (opts.stats.completeness.length === 0) {
    children.push(emptyMessage("No exam records exist for this scope and period."));
  } else {
    children.push(completenessTable(opts.stats.completeness));
  }
  children.push(new Paragraph({
    spacing: { before: 120 },
    children: [new TextRun({ text: "Note: color vision is not currently a captured field in this system and cannot be reported here; audiometry is stored as free text rather than measured dB thresholds, so only entries with a parseable severity keyword or dB figure are classified above.", italics: true, size: 18, color: "555555" })],
  }));

  // 10. Per-company breakdown — only when scope is "all" or "nonPrimary",
  // so an aggregate figure never silently hides a problem isolated to one
  // company.
  if (opts.companyBreakdown && opts.companyBreakdown.length > 0) {
    children.push(sectionHeading("Per-Company Breakdown"));
    for (const cb of opts.companyBreakdown) {
      children.push(subHeading(cb.companyName));
      children.push(new Paragraph({ spacing: { after: 120 }, children: [new TextRun({ text: companyBreakdownNarrative(cb.headcount, cb.examined, cb.keyFindings) })] }));
      children.push(dataTable(["Metric", "Value"], [["Headcount", String(cb.headcount)], ["Examined", String(cb.examined)]]));
    }
  }

  return children;
}

// Purely template-driven: one generic sentence per component whose
// non-normal share is large enough to warrant a suggested action, using the
// same denominators as the section above (never a fabricated diagnosis or
// treatment plan) — the DRAFT banner above makes clear a clinician must
// review before anything here is acted on.
function buildDraftRecommendations(stats: ApeComprehensiveStats): string[] {
  const lines: string[] = [];
  for (const c of stats.components) {
    if (!CLASSIFIED_COMPONENT_KEYS.has(c.key) || c.recordedCount < 5) continue;
    const nonNormal = c.tally.filter((t) => t.label !== "Normal").reduce((sum, t) => sum + t.count, 0);
    const share = nonNormal / c.recordedCount;
    if (share >= 0.2) {
      lines.push(`${c.label}: ${nonNormal} of ${c.recordedCount} recorded (${pct(nonNormal, c.recordedCount)}) fall outside the Normal band — consider scheduling targeted follow-up screening for the affected employees listed above.`);
    }
  }
  if (stats.followUps.some((f) => f.urgency === "High")) {
    lines.push("One or more High-urgency findings are on file — prioritize clinician review of the individuals listed in the High Urgency table above.");
  }
  return lines;
}
